-- ================================================================
-- Superstore Sales Analysis — SQL Queries
-- ================================================================
-- These queries answer 5 core business questions using SQLite.
-- Run against: data/superstore.db (generated by analysis.py)
-- ================================================================


-- ── Q1: Year-over-Year Revenue & Profit Trend ──────────────────
-- Business Question: Is the company growing? Are margins improving?
-- Insight: 2016 was peak revenue ($604K). 2017 margin hit 52.2% —
--          best of any year, suggesting improved cost discipline.

SELECT
    Year,
    SUM(Sales)                                                        AS Total_Revenue,
    SUM(Profit)                                                       AS Total_Profit,
    ROUND(CAST(SUM(Profit) AS FLOAT) / SUM(Sales) * 100, 1)          AS Profit_Margin_Pct,
    SUM(Sales) - LAG(SUM(Sales)) OVER (ORDER BY Year)                AS YoY_Revenue_Change,
    ROUND(
        (CAST(SUM(Sales) AS FLOAT) - LAG(SUM(Sales)) OVER (ORDER BY Year))
        / LAG(SUM(Sales)) OVER (ORDER BY Year) * 100, 1
    )                                                                  AS YoY_Growth_Pct
FROM orders
GROUP BY Year
ORDER BY Year;


-- ── Q2: Profit by Category & Sub-Category ─────────────────────
-- Business Question: Which product lines drive the most profit?
--                   Which are high-volume but low-margin?
-- Insight: Cutting Edge has the highest margin (51.5%).
--          Xbox Games is the #1 sub-category by profit.
--          Bookcases (Supplies) have the lowest margin at 39.6% — a flag.

SELECT
    Category1                                                         AS Category,
    "Sub-Category1"                                                   AS Sub_Category,
    COUNT(*)                                                          AS Order_Count,
    SUM(Sales)                                                        AS Revenue,
    SUM(Profit)                                                       AS Profit,
    ROUND(CAST(SUM(Profit) AS FLOAT) / SUM(Sales) * 100, 1)          AS Margin_Pct,
    RANK() OVER (ORDER BY SUM(Profit) DESC)                           AS Profit_Rank
FROM orders
GROUP BY Category1, "Sub-Category1"
ORDER BY Profit DESC;


-- ── Q3: Regional Performance ──────────────────────────────────
-- Business Question: Which regions are most valuable?
--                   Is any region underperforming on margin?
-- Insight: West leads in revenue ($661K) but Central has the
--          highest margin (54.7%) with fewer orders — efficiency win.
--          East has the lowest margin (47.8%) — worth investigating.

SELECT
    Region1                                                           AS Region,
    COUNT(*)                                                          AS Orders,
    COUNT(DISTINCT "Customer Name1")                                  AS Unique_Customers,
    SUM(Sales)                                                        AS Revenue,
    SUM(Profit)                                                       AS Profit,
    ROUND(CAST(SUM(Profit) AS FLOAT) / SUM(Sales) * 100, 1)          AS Margin_Pct,
    ROUND(CAST(SUM(Sales) AS FLOAT) / COUNT(DISTINCT "Customer Name1"), 0)
                                                                      AS Revenue_Per_Customer
FROM orders
GROUP BY Region1
ORDER BY Profit DESC;


-- ── Q4: Top 10 Customers by Profit ────────────────────────────
-- Business Question: Who are our most valuable customers?
-- Insight: Top 3 customers (Sean Miller, Tamara Chand, Sanjit Chand)
--          average 80%+ margin — far above company average of 50.5%.
--          These are VIP accounts worth protecting with dedicated support.

SELECT
    "Customer Name1"                                                  AS Customer,
    Segment1                                                          AS Segment,
    COUNT(*)                                                          AS Orders,
    SUM(Sales)                                                        AS Revenue,
    SUM(Profit)                                                       AS Profit,
    ROUND(CAST(SUM(Profit) AS FLOAT) / SUM(Sales) * 100, 1)          AS Margin_Pct,
    ROUND(CAST(SUM(Sales) AS FLOAT) / COUNT(*), 0)                   AS Avg_Order_Value
FROM orders
GROUP BY "Customer Name1", Segment1
ORDER BY Profit DESC
LIMIT 10;


-- ── Q5: Discount Impact on Margin ─────────────────────────────
-- Business Question: Are our discounts helping or hurting us?
-- Insight: Margins hold surprisingly well across discount tiers.
--          The 1-10% tier actually has the HIGHEST margin (54.1%).
--          Flag: 788 orders at 50%+ discount — review these for necessity.

SELECT
    CASE
        WHEN Discount = 0     THEN '0% — No Discount'
        WHEN Discount <= 0.10 THEN '1–10%'
        WHEN Discount <= 0.20 THEN '11–20%'
        WHEN Discount <= 0.30 THEN '21–30%'
        WHEN Discount <= 0.50 THEN '31–50%'
        ELSE                       '50%+'
    END                                                               AS Discount_Tier,
    COUNT(*)                                                          AS Orders,
    ROUND(CAST(COUNT(*) AS FLOAT) / (SELECT COUNT(*) FROM orders) * 100, 1)
                                                                      AS Pct_of_Orders,
    SUM(Sales)                                                        AS Revenue,
    SUM(Profit)                                                       AS Profit,
    ROUND(CAST(SUM(Profit) AS FLOAT) / SUM(Sales) * 100, 1)          AS Margin_Pct
FROM orders
GROUP BY Discount_Tier
ORDER BY MIN(Discount);


-- ── BONUS: Monthly Revenue Trend ──────────────────────────────
-- For time-series visualization in the dashboard.

SELECT
    Month,
    Year,
    SUM(Sales)   AS Revenue,
    SUM(Profit)  AS Profit,
    COUNT(*)     AS Orders
FROM orders
GROUP BY Month, Year
ORDER BY Month;
